# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\gui\pzh-lottery.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 372)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 931, 351))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_showPeople = QtWidgets.QLabel(self.frame)
        self.label_showPeople.setGeometry(QtCore.QRect(30, 40, 700, 297))
        self.label_showPeople.setAutoFillBackground(False)
        self.label_showPeople.setText("")
        self.label_showPeople.setObjectName("label_showPeople")
        self.textEdit_luckyPeopleBoard = QtWidgets.QTextEdit(self.frame)
        self.textEdit_luckyPeopleBoard.setGeometry(QtCore.QRect(750, 90, 161, 171))
        self.textEdit_luckyPeopleBoard.setObjectName("textEdit_luckyPeopleBoard")
        self.pushButton_load = QtWidgets.QPushButton(self.frame)
        self.pushButton_load.setGeometry(QtCore.QRect(790, 10, 75, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.lineEdit_luckyPeople = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_luckyPeople.setGeometry(QtCore.QRect(830, 50, 71, 31))
        self.lineEdit_luckyPeople.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_luckyPeople.setObjectName("lineEdit_luckyPeople")
        self.pushButton_go = QtWidgets.QPushButton(self.frame)
        self.pushButton_go.setGeometry(QtCore.QRect(790, 290, 75, 41))
        self.pushButton_go.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_go.setObjectName("pushButton_go")
        self.label_luckyPeople = QtWidgets.QLabel(self.frame)
        self.label_luckyPeople.setGeometry(QtCore.QRect(750, 50, 71, 31))
        self.label_luckyPeople.setObjectName("label_luckyPeople")
        self.lineEdit_srcXlsx = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_srcXlsx.setGeometry(QtCore.QRect(80, 10, 671, 21))
        self.lineEdit_srcXlsx.setObjectName("lineEdit_srcXlsx")
        self.label_peopleData = QtWidgets.QLabel(self.frame)
        self.label_peopleData.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_peopleData.setObjectName("label_peopleData")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_load.setText(_translate("MainWindow", "Load"))
        self.lineEdit_luckyPeople.setText(_translate("MainWindow", "5"))
        self.pushButton_go.setText(_translate("MainWindow", "Go"))
        self.label_luckyPeople.setText(_translate("MainWindow", "Lucky People:"))
        self.label_peopleData.setText(_translate("MainWindow", "People data:"))
